### ISSUE TITLE
Suggestion for the readme.md file

### ISSUE THREAD

**Issue by rmdes** [kylewm/KnownInstagramShim#1]
Can you specify that the folder of the plugin MUST be called : instagramshim
to appear on the plugin list on the install instruction ? 

thanks

**Comment by ghost** [comment]
Mine is called "InstagramShim"

**Comment by rmdes** [comment]
Trying with capitalized first letters to see If i can go to the setup screen of that plugin to insert my instagram handle..

**Comment by rmdes** [comment]
Confirmed : name MUST BE "InstagramShim"
with first letter capitalized. 
![selection_007](https://cloud.githubusercontent.com/assets/12155003/16007758/a1bfeefe-3174-11e6-9544-8e0938f9be89.png)

**Comment by karadaisy** [comment]
I don't really understand, `InstagramShim` is the standard format for all Known plugins right? If you'd like to add something to the README, I'm more than happy to merge it. Thanks!

**Comment by karadaisy** [comment]
Thank you for pointing this out, btw!
